### PR TITLE
This repo covers all the codes shown in video.

### PR DESCRIPTION
**Pull request by AhmadRaju007**
I think this might be helpful for those who are doing mistakes watching the video. If there is any problem or any issue with code sharing please feel free to knock me rajuahmad6789@gmail.com

### CODE REVIEW

**Comment by Sabhay00** [comment]
is this a completely working code?

**Comment by AhmadRaju007** [comment]
yes, it is.

**Comment by theprogrammingking** [comment]
hi suckers

**Review by mrmango1 — APPROVED** [review]

**Review by AliMendoza — APPROVED** [review]

**Review by Meloyg — APPROVED** [review]

**Comment by luisalbertmschz** [comment]
In my opinion, I think that attributions are being taken to share the code of the repository that do not correspond... he makes the videos for a reason, to teach us to learn and see the process... if you do not want to do that, he offers the option of that you buy his template as an aid to his work (the work of sharing with us how the process of achieving those designs is)

Let whoever wants to learn do it for their account and whoever doesn't, help by buying the template....

**Comment by AhmadRaju007** [comment]
@luisalbertmschz thanks for your opinion.

Personally I dont know owner of this project or what his motive is. I think he has necessary permissions to remove the pull request if he finds it not useful. As he has not mentioned any monetary terms of selling the project, I think he is ok with this PR.

Having said that if what you mentioned above is the actual case and owner of this repo wants this PR to be removed, I give you my assurance that I will remove it in no time.  

Thanks again.

**Pull request closed without merging**
